### ISSUE TITLE
Fix: list words starting with lower or upper case

### ISSUE THREAD

**Issue by DumiJDev** [W1ldr/dictionary-api#15]
The search is not insensitive case, there is difference between 'b' and 'B', there 'Brasil' and 'brasil' words, in both is the same.

**Comment by DumiJDev** [comment]
Brasil can be found searching with 'B' in the first page, and brasil can be found in the 229th page searching with 'b'

**Comment by DumiJDev** [comment]
brasil

![image](https://github.com/W1ldr/dictionary-api/assets/72232653/64bc41f7-5575-45d6-939b-83972d30212f)

**Comment by W1ldr** [comment]
Hey @DumiJDev, thanks for the inputs, changes will be made and the routes /words/starting_with/ will not be sensitive case

**Comment by DumiJDev** [comment]
Brasil

![image](https://github.com/W1ldr/dictionary-api/assets/72232653/14ea249e-1e68-4669-b0e6-829a632446ef)
